spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${POSTGRESQL_ROOT}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-dev.sql

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace