spring:
  application:
    name: discodeit
  profiles:
    active: prod

# actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100 # global
    show-sql: false # logging이랑 겹침.
    open-in-view: false # PC를 언제까지 유지할지 결정. (transaction or view)

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

# custom
discodeit:
  storage:
    local:
      root-path: ./uploads

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.jdbc.bind: trace
    root: info

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 4.0.1
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: local
      path: ${discodeit.storage.local.root-path}
    multipart:
      max-file-size: ${management.servlet.multipart.max-file-size:10MB}
      max-request-size: ${management.servlet.multipart.max-request-size:30MB}