spring:
  application:
    name: discodeit
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: discodeit
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true
    open-in-view: false # true: PC를 언제까지 유지할지
    hibernate:
      ddl-auto: create

discodeit:
  repository:
    type: jcf # 주석처리(jcf) || "jcf" || "file"
    file-directory: rdata

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.jdbc.bind: trace