server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${POSTGRESQL_ROOT}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: discodeit